# Generated by Django 5.1.4 on 2025-01-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[], max_length=20)),
                ('open', models.BooleanField(default=False)),
                ('start_at', models.DateField(null=True)),
                ('end_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ('-created_at',),
            },
        ),
    ]
