# Generated by Django 5.1.4 on 2025-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.AddField(
            model_name='event',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
