# Generated by Django 5.1.4 on 2025-01-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('seat_grades', '0001_initial'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('reserved', models.BooleanField()),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('seat_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seat_grades.seat_grade')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.slot')),
            ],
        ),
    ]
