# Generated by Django 5.1.4 on 2025-01-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.slot'),
        ),
    ]
