# Generated by Django 5.1.4 on 2025-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_alter_seat_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('reserved', 'Reserved'), ('payed', 'Payed')], default='open', max_length=20),
        ),
    ]
