# Generated by Django 5.1.4 on 2025-01-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('seats', '0003_seat_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='bookings.booking'),
        ),
    ]
